#pragma config(Motor,  motorA,          m_izquierdo,   tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          m_derecho,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          brazo,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void avanzar(int velocidad, int tiempo) {
	motor[m_izquierdo] = velocidad;
	motor[m_derecho] = velocidad;
	wait1Msec(tiempo);
}
void girar_izquierda(int velocidad_izquierda, int velocidad_derecha, int tiempo) {
	motor[m_izquierdo] = velocidad_izquierda;
	motor[m_derecho] = velocidad_derecha;
	wait1Msec(tiempo);
}
void levantar_objeto() {
    motor[brazo] = 50;  // Levantar el brazo a una velocidad de 50
    wait1Msec(1000);    // Mantener el brazo levantado durante 1 segundo
    motor[brazo] = 0;   // Detener el motor del brazo
}
void soltar_objeto() {
    motor[brazo] = -50; // Bajar el brazo a una velocidad de -50
    wait1Msec(1000);    // Mantener el brazo bajado durante 1 segundo
    motor[brazo] = 0;   // Detener el motor del brazo
}
task main(){
    avanzar(35, 2000);
    girar_izquierda(35, 45, 3000);
    girar_izquierda(50, 0, 200);
    avanzar(40, 2000);
    girar_izquierda(30, 20, 3000);
    levantar_objeto();
    avanzar(-35, 2000); // Retroceder durante 2 segundos
    soltar_objeto();
}
